### ISSUE TITLE
Tensorflow implementation

### ISSUE THREAD

**Issue by Hokie23** [HazyResearch/structured-nets#1]
Just wanted to know if the TF implementation is complete or does the package support only pytorch?

**Comment by tridao** [comment]
We only support Pytorch. 
There is some Tensorflow code for some simple matrix classes, but there's no implementation of the fast multiplication in Tensorflow. The fast multiplication in Pytorch is in https://github.com/HazyResearch/structured-nets/tree/master/pytorch/structure

**Comment by Hokie23** [comment]
Got it, thank you for making the implementation public! Are you interested in collaboration or DMs?

**Comment by tridao** [comment]
We are happy to help if you need more info on how to implement the algorithm or how to use the code.
