### ISSUE TITLE
C++ error thrown when installing diag_mult_cuda for pytorch

### ISSUE THREAD

**Issue by jzilly** [HazyResearch/structured-nets#2]
When installing the diag_mult_cuda package, the following error gets thrown for my system. This may be related to a new pytorch version. Do you have any insight on this?

Some system specs:
Ubuntu 16.04
Python 3.7
Pytorch version 1.0.1.post2

Output of command: python setup.py install
```
running install
running bdist_egg
running egg_info
writing diag_mult_cuda.egg-info/PKG-INFO
writing dependency_links to diag_mult_cuda.egg-info/dependency_links.txt
writing top-level names to diag_mult_cuda.egg-info/top_level.txt
reading manifest file 'diag_mult_cuda.egg-info/SOURCES.txt'
writing manifest file 'diag_mult_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'diag_mult_cuda' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/idscadmin/.local/lib/python3.7/site-packages/torch/lib/include -I/home/idscadmin/.local/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/idscadmin/.local/lib/python3.7/site-packages/torch/lib/include/TH -I/home/idscadmin/.local/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.7m -c diag_mult_cuda.cpp -o build/temp.linux-x86_64-3.7/diag_mult_cuda.o -g -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=diag_mult_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
diag_mult_cuda.cpp: In function ‘at::Tensor subdiagKrylov(at::Tensor, at::Tensor, int)’:
diag_mult_cuda.cpp:28:33: error: could not convert ‘v.at::Tensor::type()’ from ‘at::Type’ to ‘c10::IntList {aka c10::ArrayRef<long int>’
   auto output = at::empty(v.type(), at::IntList{m, batchSize, n});
                                 ^
diag_mult_cuda.cpp:32:62: error: expected primary-expression before ‘float’
     subdiagMultGPU(subdiag.data<float>(), output[i - 1].data<float>(), output[i].data<float>(), 0, -1, batchSize, n, false);
                                                              ^
diag_mult_cuda.cpp:32:87: error: expected primary-expression before ‘float’
     subdiagMultGPU(subdiag.data<float>(), output[i - 1].data<float>(), output[i].data<float>(), 0, -1, batchSize, n, false);
                                                                                       ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by tridao** [comment]
Yep, I think it's because of new Pytorch version. The C++/CUDA extension was written for Pytorch 0.4, and we haven't had time to update it.
I'm not positive, but I don't think we use the `diag_mult_cuda` function in any of the experiment though.

**Comment by tridao** [comment]
Please let us know if `diag_mult_cuda` is needed. I'll try to take a look then and hopefully update it for Pytorch 1.0.
We appreciate you trying out our code.

**Comment by jzilly** [comment]
Do know what one might have to change so that the C++/CUDA extension works? It (diag_mult_cuda) seems like a crucial part of the code since the Krylov matrix computations (https://github.com/HazyResearch/structured-nets/blob/master/pytorch/structure/krylov.py) use it.

**Comment by tridao** [comment]
I think it's just that the C++ extension interface of Pytorch has changed (e.g. we're supposed to include `#include <torch/extension.h>` instead of some older .h file). The Krylov code just imports that function for testing only (I think). Let me know otherwise.

**Comment by jzilly** [comment]
Makes sense. I was already including `<torch/extension.h>`. Not sure how the interface needs to change though. Do you know where I could find out?

**Comment by tridao** [comment]
I just updated the code. It should compile with Pytorch 1.0 now.

**Comment by jzilly** [comment]
Thank you! It does install now. 
Do you know how fast the code should run on cuda? Am training a layer of "LDRTridiagonalC()" which at moment runs much slower than training a linear layer. Perhaps i did not select to use CUDA somewhere.

**Comment by tridao** [comment]
Yes, LDRTridiagonal is quite slow, maybe on the order of 10x slower than Linear depending on the size (just comparing the speed of that layer only, not of the entire network).
There exists, in theory, a fast algorithm O(n log^2 n) for tridiagonal (see De Sa et al SODA 2018 Section 5), but it's complicated and hard to implement. We only implemented the fast algorithm O(n log^2 n) for LDRSubdiagonal. This implementation is in pure Pytorch (it uses FFT as a primitive). For large sizes (>= 2^13) it might be faster than Linear, but it'll still be slower for sizes smaller than that.
If you just want to try out some structured matrices, here are some suggests in order of fast to slow:
Circulant, Toeplitz, Toeplitz-like, LDRSubdiagonal, LDRTridiagonal.

**Comment by jzilly** [comment]
Perfect! Thank you again.
