### ISSUE TITLE
Use torch complex matrices

### ISSUE THREAD

**Issue by thomasahle** [HazyResearch/structured-nets#7]
Torch now (since 2020) has support for complex matrices! This allows simplifying a lot of the code in toeplitz and krylov.py.

**Comment by albertfgu** [comment]
Yes, it makes the implementation much easier - we have moved on to native complex support in recent projects. This project is old and we have no plans to maintain it, but we are happy to accept PRs for updates to the infrastructure.

**Comment by thomasahle** [comment]
Alright, as you wish :-)
Here's my PR which allows the code to be run with the current PyTorch versions: https://github.com/HazyResearch/structured-nets/pull/9
